/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VideographyRouteImport } from './routes/videography'
import { Route as VideosRouteImport } from './routes/videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VideographyRoute = VideographyRouteImport.update({
  id: '/videography',
  path: '/videography',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRoute
  '/clients': typeof ClientsRoute
  '/collections': typeof CollectionsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/photography': typeof PhotographyRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/videography': typeof VideographyRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRoute
  '/clients': typeof ClientsRoute
  '/collections': typeof CollectionsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/photography': typeof PhotographyRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/videography': typeof VideographyRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRoute
  '/clients': typeof ClientsRoute
  '/collections': typeof CollectionsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/photography': typeof PhotographyRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/videography': typeof VideographyRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability'
    | '/bookings'
    | '/clients'
    | '/collections'
    | '/login'
    | '/notifications'
    | '/photography'
    | '/portfolio'
    | '/settings'
    | '/videography'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/bookings'
    | '/clients'
    | '/collections'
    | '/login'
    | '/notifications'
    | '/photography'
    | '/portfolio'
    | '/settings'
    | '/videography'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/availability'
    | '/bookings'
    | '/clients'
    | '/collections'
    | '/login'
    | '/notifications'
    | '/photography'
    | '/portfolio'
    | '/settings'
    | '/videography'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityRoute: typeof AvailabilityRoute
  BookingsRoute: typeof BookingsRoute
  ClientsRoute: typeof ClientsRoute
  CollectionsRoute: typeof CollectionsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PhotographyRoute: typeof PhotographyRoute
  PortfolioRoute: typeof PortfolioRoute
  SettingsRoute: typeof SettingsRoute
  VideographyRoute: typeof VideographyRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videography': {
      id: '/videography'
      path: '/videography'
      fullPath: '/videography'
      preLoaderRoute: typeof VideographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityRoute: AvailabilityRoute,
  BookingsRoute: BookingsRoute,
  ClientsRoute: ClientsRoute,
  CollectionsRoute: CollectionsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PhotographyRoute: PhotographyRoute,
  PortfolioRoute: PortfolioRoute,
  SettingsRoute: SettingsRoute,
  VideographyRoute: VideographyRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
